# .github/release.yml

changelog:
  exclude:
    labels:
      - exclude
  categories:
    - title: Exciting New Features 🎉
      labels:
        - enhancement
    - title: Bug Fixes 🛠
      labels:
        - bug
        
