# .github/release.yml

changelog:
  exclude:
    labels:
      - exclude
      - cleanup
      - developer
      - documentation
      - duplicate
      - invalid
      - notabug
      - wontfix
      - question
      - performance
  categories:
    - title: New Features
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
        
